import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeToggle } from "@/components/ThemeToggle";
import { ThemeProvider } from "next-themes";
import ThemeAnimate from "@/components/ThemeAnimate";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <ThemeAnimate>
              <div className="relative min-h-screen">
                {children}
                <ThemeToggle />
              </div>
            </ThemeAnimate>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
